#120 test-feature/JobDescription: ci.yml test 로그 확인

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -53,7 +53,7 @@ jobs:
       - name: Test with Gradle
         env:
           SPRING_PROFILES_ACTIVE: test
-        run: ./gradlew test
+        run: ./gradlew test -Dspring.profiles.active=test --info --debug | grep "The following profiles are active" || echo "Profile activation line not found in debug log"
 
       # 테스트를 기반으로 JaCoCo 리포트 작성
       - name: Generate JaCoCo Report
