#120 test-feature/JobDescription: test 수정 - CI.yml test 시 커멘드 변경

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -47,7 +47,9 @@ jobs:
         run: ./gradlew build -x test
 
       - name: Check application-test.yml exists
-        run: cat src/test/resources/application-test.yml || echo "application-test.yml not found"
+        run:
+          cat src/test/resources/application-test.yml || echo "application-test.yml not found"
+          cat src/main/resources/application-test.yml || echo "application-test.yml not found"
 
       - name: Print environment
         run: printenv
