#120 test-feature/JobDescription: ci.yml 원복

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -47,9 +47,7 @@ jobs:
         run: ./gradlew build -x test
 
       - name: Check application-test.yml exists
-        run:
-          cat src/test/resources/application-test.yml || echo "application-test.yml not found"
-          cat src/main/resources/application-test.yml || echo "application-test.yml not found"
+        run: cat src/main/resources/application-test.yml || echo "application-test.yml not found"
 
       - name: Print environment
         run: printenv
@@ -60,15 +58,11 @@ jobs:
           cp src/test/resources/application-test.yml src/main/resources/
 
       - name: Check application-test.yml exists
-        run:
-          cat src/main/resources/application-test.yml || echo "application-test.yml not found"
-          cat src/test/resources/application-test.yml || echo "application-test.yml not found"
+        run: cat src/main/resources/application-test.yml || echo "application-test.yml not found"
 
       # 테스트 진행
       - name: Test with Gradle
         run: ./gradlew test
-        env:
-          SPRING_PROFILES_ACTIVE: test
 
       # 테스트를 기반으로 JaCoCo 리포트 작성
       - name: Generate JaCoCo Report
